export const plannedItems = [
  { title: "AI Video Script Generator", description: "Automatically create viral-ready scripts for YouTube and TikTok based on trending keywords and high-retention hooks." },
  { title: "WhatsApp Marketing Automation", description: "A complete guide and toolkit to automate customer support and sales broadcasts using the official WhatsApp Business API." },
  { title: "The 'Ghostwriter' Ebook Kit", description: "Master the art of writing and selling ebooks under your own brand with 20+ ready-to-use digital templates." },
  { title: "SEO Backlink Strategy 2026", description: "Learn the modern way to build high-authority backlinks without getting penalized by the latest Google search algorithms." },
  { title: "High-Ticket Closing Scripts", description: "Professional sales frameworks designed for Zoom calls and webinars to help you close $2,000+ deals with confidence." },
  { title: "SaaS Landing Page Framework", description: "A collection of high-converting landing page designs proven to reduce bounce rates and increase user sign-ups." },
  { title: "The Silent Influencer Method", description: "How to build a massive personal brand and monetize your following without ever showing your face on camera." },
  { title: "Cold Calling Mastery", description: "Turn cold leads into warm appointments using our proven psychological scripts and objection-handling techniques." },
  { title: "Digital Product Launchpad", description: "A step-by-step system to research, create, and launch your first digital product in less than 30 days." },
  { title: "Facebook Group Growth Hacks", description: "How to build a highly engaged private community that acts as a consistent lead-generation machine for your business." },
  { title: "The 'No-Code' MVP Guide", description: "Build and test your startup idea using powerful no-code tools like Bubble and Adalo before hiring expensive developers." },
  { title: "UGC Creator Blueprint", description: "Start a career as a User-Generated Content creator. Learn how to pitch brands and create high-quality ads from your phone." },
  { title: "Pinterest for E-commerce", description: "Drive thousands of targeted visitors to your Shopify or Etsy store using organic Pinterest SEO and viral pins." },
  { title: "Customer Retention Secret", description: "Advanced strategies for SaaS and service-based businesses to keep clients subscribed for years, not months." },
  { title: "The Webinar Profit System", description: "Learn how to structure a 60-minute presentation that builds trust and sells your products automatically 24/7." },
  { title: "Remote Team Management", description: "A toolkit for founders to hire, train, and manage a global remote workforce using Slack, Notion, and Loom." },
  { title: "Credit Score Repair Guide", description: "Practical, legal steps to help customers understand and improve their credit scores for better financial opportunities." },
  { title: "The Millionaire Morning Habits", description: "Daily routines and productivity frameworks used by top 1% entrepreneurs to maintain focus and high energy." },
  { title: "TikTok Shop Mastery", description: "Everything you need to know about setting up and scaling a profitable shop directly inside the TikTok app." },
  { title: "Brand Identity Design Kit", description: "A collection of professional templates and guides to help you create a consistent brand voice, logo, and color palette." },
  { title: "Automated Lead Magnet Kit", description: "Build high-converting PDF guides and checklists that grow your email list while you sleep." },
  { title: "The 'Perfect' Pitch Deck", description: "Figma and PPT templates designed to help startup founders raise investment from venture capitalists." },
  { title: "Reddit Marketing Blueprint", description: "Learn how to promote your brand on Reddit organically without getting banned or looking like a spammer." },
  { title: "Faceless YouTube Empire", description: "Run multiple profitable YouTube channels using AI voiceovers and stock footage for 100% passive income." },
  { title: "Agency Scaling SOPs", description: "Standard Operating Procedures for hiring, client reporting, and project management to help your agency run on autopilot." },
  { title: "Affiliate SEO Strategy", description: "Rank niche websites on Google and earn consistent commissions from Amazon and other high-paying affiliate programs." },
  { title: "LinkedIn Authority Builder", description: "How to write professional posts that get thousands of views and establish you as an industry expert." },
  { title: "Podcast Monetization Guide", description: "Learn how to land high-paying sponsors and sell premium subscriptions for your audio content." },
  { title: "Copywriting for Conversions", description: "A deep dive into writing sales pages, ads, and emails that trigger an immediate 'Buy' response from readers." },
  { title: "Twitter/X Thread Mastery", description: "The exact framework for writing viral threads that build your following and drive massive website traffic." },
  { title: "Etsy Digital Shop Secret", description: "Launch a passive income stream selling planners, wall art, and templates on the world’s biggest creative marketplace." },
  { title: "Web3 Job Finder", description: "A roadmap to finding high-paying roles in crypto and blockchain, even if you’re not a technical developer." },
  { title: "The Upsell Framework", description: "Learn how to increase your average order value by adding strategic upsells and order bumps to your checkout process." },
  { title: "GMB Domination", description: "Step-by-step guide to ranking your local business in the Google Maps 'Top 3' to get more calls and customers." },
  { title: "Mobile App Marketing", description: "Proven strategies to get your first 10,000 app downloads using organic search and low-cost influencer ads." },
  { title: "Subscription Box Success", description: "How to launch and scale a physical subscription box business with recurring monthly revenue." },
  { title: "The Art of Storytelling", description: "Master emotional marketing to build a loyal 'cult-like' following that buys everything you release." },
  { title: "Sales Funnel Audit", description: "Learn how to identify and fix the 'leaks' in your sales funnel that are costing you potential customers and profit." },
  { title: "Print on Demand Profits", description: "Design and sell custom t-shirts and hoodies globally without ever touching the physical inventory." },
  { title: "The Founder’s Productivity Tool", description: "Advanced Notion templates to help you track your goals, projects, and daily tasks in one central hub." },
  { title: "Skool Community Guide", description: "Build and monetize a private paid community on Skool to share your expertise and earn recurring income." },
  { title: "Influencer Outreach Scripts", description: "The exact templates to use when reaching out to creators for brand collaborations and shoutouts." },
  { title: "Zero-Cost Marketing", description: "50 creative ways to promote your business and get customers without spending a single rupee on paid ads." },
  { title: "The 'Consultant' Blueprint", description: "Transform your skills into a high-paying consulting business. Includes pricing strategies and client intake forms." },
  { title: "Email Deliverability Fix", description: "Technical guide to ensure your emails land in the 'Primary' inbox instead of the spam or promotions folder." },
  { title: "Mindset for Founders", description: "Daily mental exercises to stay resilient, overcome the fear of failure, and maintain a winning entrepreneurial attitude." },
  { title: "Real Estate Lead Gen", description: "Hyper-local Facebook and Instagram ad strategies to find motivated buyers and sellers in your specific city." },
  { title: "Upwork Profile Secrets", description: "How to build a 5-star freelancer profile that attracts high-paying long-term clients from around the world." },
  { title: "Website Speed Mastery", description: "Step-by-step technical guide to making your site load in under 1 second for better SEO and user experience." },
  { title: "The Future of AI Business", description: "A comprehensive look at the emerging AI tools and opportunities that will dominate the market in 2026." }
];
